[advisories]
version = 2
yanked = "warn"

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-3-Clause",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
